### ISSUE TITLE
Don't save 'exit' to history

### ISSUE THREAD

**Issue by bdealey** [senzing-garage/g2explorer#97]
During our dataloading periods, I frequently log into G2Exployer to run the 'quickLook' command.  Its a four step process for me to get onto the EC2 server running senzing console, to select the service account on the EC2 server, to get into G2Explorer and run quickLook.  
All of these steps gets saved in some history file, and may times I just do a single up-arrow to bring up the appropriate command for each of these steps.  However, when I get to G2Explorer, the single up-arrow often time brings up 'exit' instead of 'quickLook' and I exit from G2Explorer.  Doesn't seen necessary to save the 'exit' command as part of the history.

**Comment by jbutcher21** [comment]
Understood, I will stop saving this in the 4.0 release.
