### ISSUE TITLE
Run G2Explorer/quickLook from a bash command

### ISSUE THREAD

**Issue by bdealey** [senzing-garage/g2explorer#98]
I use quickLook often during heavy loads to help me monitor the loading. I would like to run 'quickLook' from a bash script, so it may run periodically automatically or possibly even parse the results out and display it in a dashboard.

It would be great if I could pass in 'quickLook' as a parameter to G2Explorer.py to make that one command non-interactive. Something like
G2Explorer.py -q  [Just run QuickLook and then exit back to command prompt]
or even
G2Explorer.py -C 'quickLook'  [Run the command passed in as  a parameter and then exit back to command prompt]

I could however see a case for G2Command.py where I could pass in a 'reevaluateEntity XXXXX' command from a bash script to process a whole batch of entities.  (Let me know if you would like me to file a separate issues for G2Command)

**Comment by jbutcher21** [comment]
So a better (and  faster) way to monitor a load is to "select count(*) from dsrc_account" directly from the database.  Also the API call quickLook is using is going away in 4.0.  For those reasons I am closing this request.  But do let me know if you still need help monitoring a load.
